stages:
    - build
    - test
build-and-test:
  image: "astral/uv:python$VERSION-bookworm"
  parallel:
    matrix:
      - VERSION: ['3.10', '3.11', '3.12', '3.13', '3.14']
  stage: build
  variables:
    TWINE_USERNAME: $TWINE_USERNAME
    TWINE_PASSWORD: $TWINE_PASSWORD
  before_script:
    - git config --global user.email $GITLAB_USER_EMAIL
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_FQDN}/DynAA/cDynAA.git
  script:
    - python -m venv venv && source venv/bin/activate
    - cd cDynAA && make wheel && for whl in pydynaa*.whl; do uv pip install "$whl" || :; done && cd ..
    - uv pip install .[testing]
    - pytest
ruff:
  image: astral/uv:python3.11-bookworm
  stage: build
  allow_failure: true
  script:
    - python -m venv venv && source venv/bin/activate
    - uv pip install .[testing]
    - ruff check . --diff
    - ruff format . --diff
examples-run:
  image: astral/uv:python3.11-bookworm
  stage: build
  variables:
    TWINE_USERNAME: $TWINE_USERNAME
    TWINE_PASSWORD: $TWINE_PASSWORD
  before_script:
    - git config --global user.email $GITLAB_USER_EMAIL
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_FQDN}/DynAA/cDynAA.git
    - set -Eeuo pipefail   # fail on error, unset vars; fail pipelines in pipes
  allow_failure: true
  script:
    - python -m venv venv && source venv/bin/activate
    - cd cDynAA && make wheel && for whl in pydynaa*.whl; do uv pip install "$whl" || :; done && cd ..
    - uv pip install .[testing]
    - uv pip install -r examples/examples_requirements.txt
    - cd examples
    - echo "#!/bin/bash" >> test.sh
    - echo "set -e" >> test.sh
    - for file in *.py; do echo "python examples/$file"; done >> test.sh
    - chmod +x test.sh
    - cd ..
    - ./examples/test.sh
